function [F]=solve_forlambdao_help(x,para,mm_Th,mm_z,mm_omegas,elast_s,alpha_mat,ii_cd,mm_lambda_j,dd_pi_type,bb,nn,min_lo,max_lo)

o_b=bb(1);n_o=nn(1);n_g=nn(3);theta_w=para(1);rho=para(2);

index=[1:1:n_o];index(o_b)=[];
dd_pi_type=permute(dd_pi_type,[3,1,2]);
alpha_bar=(1-alpha_mat).*alpha_mat.^(alpha_mat.*(1-alpha_mat).^(-1));
lambdao_rel=x;
%%%%%%%%%%demand
a_rel=mm_omegas(index)/mm_omegas(o_b);
rel_d=(a_rel.*(lambdao_rel).^(-rho));   
%%%%%%%%%%supply
tildeA=1+nansum(a_rel.^(1/rho).*(rel_d).^((rho-1)/rho),1);
lambdao_b=((mm_omegas(o_b).*tildeA).^(-1)).^(1/(1-rho));     
lambdao_rel_in=[lambdao_rel(1:o_b-1);1;lambdao_rel(o_b:n_o-1)];
lambda_o=lambdao_b.*lambdao_rel_in;
aa1=(alpha_mat.*(1-alpha_mat).^(-1)).^((1-elast_s).^(-1)).*repmat(mm_lambda_j,[1,n_g,1]).^((elast_s).*((elast_s-1)).^(-1));
aa2=(1-alpha_mat).^((elast_s-1).^(-1)).*repmat(lambda_o,[1,n_g,1]).^((elast_s).*((elast_s-1)).^(-1));
x_tilda=(aa2-aa1).^((elast_s-1).*((elast_s)).^(-1));
mm_xtilda=x_tilda;
aa1=repmat(mm_lambda_j,[1,n_g,1]).^((-alpha_mat).*(1-alpha_mat).^(-1));
aa2=repmat(lambda_o,[1,n_g,1]).^((1).*((1-alpha_mat)).^(-1));
mm_xtilda_cd=alpha_bar.*aa1.*aa2;
mm_xtilda(ii_cd,:,:)=mm_xtilda_cd(ii_cd,:,:);
[mm_xtilda]=corr_corner(mm_xtilda);
num=(mm_z.*mm_xtilda).^theta_w;
den=repmat(nansum(num,1),[n_o,1,1]);
mm_pi_oj_gh=num.*(den).^(-1); 
T_h_st=repmat(permute(mm_Th,[3,1,2]),[n_o,1,1]);
eff_byt=(T_h_st).^(1/theta_w).*gamma(1-1/theta_w).*mm_pi_oj_gh.^(-1/theta_w+1);
mm_eeff=eff_byt.*repmat(dd_pi_type,[n_o,1,1]);    
mm_k=mm_eeff.*(alpha_mat.*(1-alpha_mat).^(-1).*mm_xtilda.*mm_z.*repmat(mm_lambda_j,[1,n_g,1]).^(-1).*mm_z.^(-elast_s)).^((1-elast_s).^(-1));
mm_k(mm_z==0)=nan;
mm_y=(alpha_mat.*mm_k.^elast_s+(1-alpha_mat).*(mm_z.*mm_eeff).^elast_s).^((elast_s).^(-1));
mm_yo=nansum(mm_y,2);
mm_k_cd=mm_eeff.*mm_z.*(alpha_mat.*repmat(lambda_o,[1,n_g,1])...
    .*repmat(mm_lambda_j,[1,n_g,1]).^(-1)).^((1-alpha_mat).^(-1));
mm_k_cd(mm_z==0)=nan;
mm_y_cd=mm_k_cd.^alpha_mat.*(mm_z.*mm_eeff).^(1-alpha_mat);
mm_yo_cd=nansum(mm_y_cd,2);
mm_yo(ii_cd,:,:)=mm_yo_cd(ii_cd,:,:);
rel_s=(mm_yo(index))/(mm_yo(o_b));
%%%%%%%%%%update
F=rel_d-rel_s;
F(lambdao_rel<=0)=10^10;
